version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2-node
    working_directory: ~/mkt-api
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler:2.1.4
      - run:
          name: Set bundle config
          command: bundle config set path 'vendor/bundle'
      - run:
          name: Run bundle
          command: bundle install

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main

# Testing CircleCI