version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-stretch-node
    working_directory: ~/mkt-api
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: gem install bundler:2.1.4
      - run:
          name: Set bundle config
          command: bundle config set path 'vendor/bundle'
      - run:
          name: bundle
          command: bundle install
      - run:
          name: Testing...
          command: rails test

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main